from django.db import models
from django.contrib.auth.models import User


# ---------------------------------------------------------
# Store additional information about each user.
# ---------------------------------------------------------

class UserDetail(models.Model):

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='detail'
    )

    username = models.CharField(
        max_length=150,
        unique=True
    )

    email = models.EmailField(
        unique=True
    )

    profile_picture = models.ImageField(
        upload_to='profile_pics/', blank=True, null=True
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return self.username


# ---------------------------------------------------------
# Store every cold email generated by the user.
# ---------------------------------------------------------

class EmailRequest(models.Model):

    TONE_CHOICES = [
        ('formal', 'Formal'),
        ('friendly', 'Friendly'),
        ('confident', 'Confident'),
        ('enthusiastic', 'Enthusiastic'),
    ]

    STATUS_CHOICES = [
        ('sent', 'Sent'),
        ('no_response', 'No Response'),
        ('replied', 'Got Reply'),
        ('interview', 'Interview Scheduled'),
        ('rejected', 'Rejected'),
        ('offer', 'Offer Received'),
    ]

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='email_requests'
    )

    company_name = models.CharField(
        max_length=255
    )

    role_title = models.CharField(
        max_length=100,
        blank=True
    )

    recipient_email = models.EmailField(blank=True)

    resume_text = models.TextField()

    # Optional resume file attached to the generated email.
    resume_file = models.FileField(
        upload_to='resumes/',
        blank=True,
        null=True
    )

    job_description = models.TextField()

    tone = models.CharField(
        max_length=20,
        choices=TONE_CHOICES,
        default='formal'
    )

    subject_line = models.CharField(
        max_length=255,
        blank=True
    )

    generated_body = models.TextField(
        blank=True
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='no_response'
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return (
            f"{self.company_name} - "
            f"{self.user.username} "
            f"({self.created_at.strftime('%Y-%m-%d')})"
        )


# ---------------------------------------------------------
# Store reusable AI-generated templates, learned over time.
# Used as a smarter fallback when all AI providers fail.
# ---------------------------------------------------------

class SavedTemplate(models.Model):

    role_title = models.CharField(max_length=100)

    tone = models.CharField(max_length=20)

    subject_line = models.CharField(max_length=255)

    generated_body = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.role_title} ({self.tone})"


# ---------------------------------------------------------
# Store scam-check results for each user.
# ---------------------------------------------------------

class ScamCheck(models.Model):

    RISK_CHOICES = [
        ('safe', 'Safe'),
        ('caution', 'Caution'),
        ('risky', 'Risky'),
    ]

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='scam_checks'
    )

    sender_email = models.CharField(
        max_length=255,
        blank=True
    )

    email_content = models.TextField()

    risk_level = models.CharField(
        max_length=10,
        choices=RISK_CHOICES
    )

    verdict_summary = models.CharField(
        max_length=255
    )

    red_flags = models.TextField(
        blank=True
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return (
            f"{self.sender_email or 'Unknown'} - "
            f"{self.risk_level} "
            f"({self.created_at.strftime('%Y-%m-%d')})"
        )


# ---------------------------------------------------------
# Store domains AI has confirmed as safe or risky over time.
# Used as a fast, reliable fallback signal when all AI
# providers are unavailable for scam analysis.
# ---------------------------------------------------------

class KnownDomain(models.Model):

    RISK_CHOICES = [
        ('safe', 'Safe'),
        ('risky', 'Risky'),
    ]

    domain = models.CharField(max_length=255, unique=True)

    risk_level = models.CharField(max_length=10, choices=RISK_CHOICES)

    confirmed_count = models.IntegerField(default=1)

    last_confirmed = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.domain} - {self.risk_level} ({self.confirmed_count}x)"


# ---------------------------------------------------------
# Store Gmail connection information for each user.
# ---------------------------------------------------------

class GmailAccount(models.Model):

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='gmail_account'
    )

    access_token = models.TextField()

    refresh_token = models.TextField()

    token_expiry = models.DateTimeField()

    connected_at = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return f"Gmail connected for {self.user.username}"