# Generated by Django 6.1.1 on 2026-09-15 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailgen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('resume_text', models.TextField()),
                ('job_description', models.TextField()),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('friendly', 'Friendly'), ('confident', 'Confident'), ('enthusiastic', 'Enthusiastic')], default='formal', max_length=20)),
                ('subject_line', models.CharField(blank=True, max_length=255)),
                ('generated_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
