# Generated by Django 6.1.1 on 2026-09-16 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailgen', '0002_emailrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScamCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(blank=True, max_length=255)),
                ('email_content', models.TextField()),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('caution', 'Caution'), ('risky', 'Risky')], max_length=10)),
                ('verdict_summary', models.CharField(max_length=255)),
                ('red_flags', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scam_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
