# Generated by Django 6.1.1 on 2026-09-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailgen', '0004_gmailaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrequest',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
