# Generated by Django 6.1.1 on 2026-09-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailgen', '0005_emailrequest_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrequest',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
