# Generated by Django 6.1.1 on 2026-09-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailgen', '0006_emailrequest_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrequest',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('no_response', 'No Response'), ('replied', 'Got Reply'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('offer', 'Offer Received')], default='no_response', max_length=20),
        ),
    ]
