# Generated by Django 6.1.1 on 2026-09-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailgen', '0007_emailrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=100)),
                ('tone', models.CharField(max_length=20)),
                ('subject_line', models.CharField(max_length=255)),
                ('generated_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailrequest',
            name='role_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
