# Generated by Django 6.1.1 on 2026-09-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailgen', '0008_savedtemplate_emailrequest_role_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
