# Generated by Django 6.1.1 on 2026-09-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailgen', '0009_userdetail_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('risky', 'Risky')], max_length=10)),
                ('confirmed_count', models.IntegerField(default=1)),
                ('last_confirmed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
